#!/usr/bin/env python
#
# Copyright 2015 gimoh
#
# This file is part of devops-utils.
#
# devops-utils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# devops-utils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with devops-utils.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import argparse
import os
import shutil
import sys
import textwrap

from subprocess import check_call, CalledProcessError


PROGS = (
    'ansible', 'ansible-doc', 'ansible-galaxy', 'ansible-playbook',
    'ansible-vault', 'fab',
    )


def run(prog, args):
    """Run the specified program."""
    os.execvp(prog, (prog,) + tuple(args))

def install():
    """Install a runner and shortcuts to all supported programs.

    The runner will execute the command it's run as via docker run.
    """
    try:
        check_call(('mountpoint', '-q', '/target'))
    except CalledProcessError:
        print(textwrap.dedent('''\
            /target is not a mountpoint

            Re-run this image with -v $HOME/.local/bin:/target
            '''))
        return 2

    print('installing runner')
    shutil.copy('external-runner', '/target/devops-utils')

    print('installing links ... ', end='')
    for prog in PROGS:
        link = os.path.join('/target', prog)
        print(' {}'.format(prog), end='')
        if os.path.exists(link):
            print(' (skip)', end='')
        else:
            os.symlink('devops-utils', link)
    print('')

def main(args=sys.argv[1:]):
    """Run a program in devops-utils container."""
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument('prog', help='program to run (e.g.: install, {})'.
                                     format(', '.join(PROGS)))

    args, prog_args = parser.parse_known_args(args)
    print({'args': args, 'prog_args': prog_args})
    
    if args.prog == 'install':
        sys.exit(install())

    run(args.prog, prog_args)


if __name__ == '__main__':
    main()
