#!/usr/bin/env python
#
# Copyright 2015 gimoh
#
# This file is part of devops-utils.
#
# devops-utils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# devops-utils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with devops-utils.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import argparse
import sys
import subprocess


PROGS = ()  ##INIT_VAR:PROGS##
DOCKER_IMAGE = 'gimoh/devops-utils'  ##INIT_VAR:DOCKER_IMAGE##


def main(args=sys.argv[1:]):
    """Run a program in devops-utils container."""
    parser = argparse.ArgumentParser(description=main.__doc__, add_help=False,
                                     prefix_chars='+')
    parser.add_argument('prog', help='program to run (e.g.: install, {})'.
                                     format(', '.join(PROGS)))
    parser.add_argument('+O', '++docker-opt', action='append',
                        help='pass specified long-style option to docker run')
    parser.add_argument('++help', action='store_true',
                        help='show this help message and exit')
    parser.set_defaults(docker_opt=[])

    args, prog_args = parser.parse_known_args(args)

    if args.help:
        parser.print_help()
        parser.exit()

    docker_opts = '-i -t --rm'.split()

    docker_opts.extend(['--%s' % opt for opt in args.docker_opt])
    cmd = ['docker', 'run']
    cmd.extend(docker_opts)
    cmd.extend([DOCKER_IMAGE, args.prog])
    cmd.extend(prog_args)

    subprocess.check_call(cmd)


if __name__ == '__main__':
    main()
