#!/usr/bin/env python
#
# Copyright 2015 gimoh
#
# This file is part of devops-utils.
#
# devops-utils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# devops-utils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with devops-utils.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import argparse
import os
import sys
import subprocess


PROGS = ()  ##INIT_VAR:PROGS##
DOCKER_IMAGE = 'gimoh/devops-utils'  ##INIT_VAR:DOCKER_IMAGE##


class DockerRunCommand(object):
    """docker run command"""
    def __init__(self, prog, prog_args):
        self.docker_args = []
        self.prog = prog
        self.prog_args = list(prog_args)

    @property
    def cmd(self):
        cmd = ['docker', 'run']
        cmd.extend(self.docker_args)
        cmd.extend([DOCKER_IMAGE, self.prog])
        cmd.extend(self.prog_args)
        return cmd

class Builders(list):
    def __call__(self, *args):
        for builder in self:
            builder(*args)

argparse_builders = Builders()
docker_run_builders = Builders()

argparse_builder = argparse_builders.append
docker_run_builder = docker_run_builders.append

@argparse_builder
def argparse_base(parser):
    self_name = os.path.basename(sys.argv[0])
    if self_name in ('external-runner', 'devops-utils'):
        parser.add_argument('prog', help='program to run (e.g.: install, {})'.
                                        format(', '.join(PROGS)))
    else:
        parser.set_defaults(prog=self_name)

    parser.add_argument('+O', '++docker-opt', action='append',
                        help='pass specified long-style option to docker run')
    parser.add_argument('++help', action='store_true',
                        help='show this help message and exit')
    parser.set_defaults(docker_opt=[])

@docker_run_builder
def docker_run_base(args, docker_run):
    docker_run.docker_args.extend('-i -t --rm'.split())

@docker_run_builder
def docker_run_opts(args, docker_run):
    docker_run.docker_args.extend(['--%s' % opt for opt in args.docker_opt])

def main(args=sys.argv[1:]):
    """Run a program in devops-utils container."""
    parser = argparse.ArgumentParser(description=main.__doc__, add_help=False,
                                     prefix_chars='+')
    argparse_builders(parser)
    args, prog_args = parser.parse_known_args(args)

    if args.help:
        parser.print_help()
        parser.exit()

    docker_run = DockerRunCommand(args.prog, prog_args)
    docker_run_builders(args, docker_run)

    subprocess.check_call(docker_run.cmd)


if __name__ == '__main__':
    main()
